require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes


AllCops:
    TargetRailsVersion: 7.1
    SuggestExtensions: false