require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

AllCops:
    SuggestExtensions: false