services:
  - type: web
    name: mente
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: RAILS_MASTER_KEY
      - key: WEB_CONCURRENCY
        value: 2 
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

# NOTE: need to add background worker for scheduled jobs (ex: CohortSchedulerJob)
