default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mentee_development

test:
  <<: *default
  database: mentee_test

production:
  <<: *default
  database: mentee_production
  username: <%= ENV["MENTEE_DATABASE_USER"] %>
  password: <%= ENV["MENTEE_DATABASE_PASSWORD"] %>
